INSERT INTO beerList (brewery_name, brewery_city, beer_name, beer_type)
VALUES
('XII West Brewing Co', 'Gilbert','The Weight', 'Scotch Ale'),
('XII West Brewing Co', 'Gilbert','Midnight Run', 'Stout'),
('XII West Brewing Co', 'Gilbert','Acquisitions', 'Belgian Farmhouse'),
('XII West Brewing Co', 'Gilbert','Jedi Juice', 'IPA'),
('XII West Brewing Co', 'Gilbert','Ethereal', 'Pale Ale'),
('XII West Brewing Co', 'Gilbert','Frontside', 'IPA'),
('XII West Brewing Co', 'Gilbert','Shwifty', 'Wheat'),
('XII West Brewing Co', 'Gilbert','Knarbar', 'Barley Wine'),
('XII West Brewing Co', 'Gilbert','K-LAX', 'IPA'),
('XII West Brewing Co', 'Gilbert','Super Beaker', 'IPA'),
('XII West Brewing Co', 'Gilbert','Blap! Blap', 'Wheat'),
('XII West Brewing Co', 'Gilbert','Mijo', 'Trippel'),
('Arizona Wilderness Brewing', 'Gilbert','ADHD#2', 'Pale Ale'),
('Arizona Wilderness Brewing', 'Gilbert', 'Boilgeist', 'IPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'Crystal Eyes', 'DIPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'DHW: Thirsty and Miserable', 'IPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'DC Mmountain DIPA', 'DIPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'O-Line IPA', 'Trippel'),
('Arizona Wilderness Brewing', 'Gilbert', 'Paiute Pale Ale', 'Pale Ale'),
('Arizona Wilderness Brewing', 'Gilbert', 'Refuge IPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'Viking Tea Time', 'Lager'),
('Arizona Wilderness Brewing', 'Gilbert', 'Saddle Mountain', 'Saison'),
('Arizona Wilderness Brewing', 'Gilbert', 'Saison Sombre', 'Saison'),
('Arizona Wilderness Brewing', 'Gilbert', 'Salome Saison', 'Saison'),
('Arizona Wilderness Brewing', 'Gilbert', 'Salt River Saison', 'Saison'),
('Arizona Wilderness Brewing', 'Gilbert', 'Baboquivari Belgian Blonde', 'Blonde'),
('Arizona Wilderness Brewing', 'Gilbert', 'Klothos Temple', 'IPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'New Brood', 'Belgian Quad IPA'),
('Arizona Wilderness Brewing', 'Gilbert', 'Grapefruit Gose', 'Gose'),
('Arizona Wilderness Brewing', 'Gilbert', 'Hummingbird Springs', 'Saison'),
('Uncle Bears Brewery', 'Phoenix', 'Fence Jumper', 'Ale'),
('Uncle Bears Brewery', 'Phoenix', 'Mandarin Wheat', 'Wheat'),
('Uncle Bears Brewery', 'Phoenix', 'Head to Tale', 'Ale' ),
('Uncle Bears Brewery', 'Phoenix', 'Ocean Beach', 'IPA' ),
('Uncle Bears Brewery', 'Phoenix', 'Bears Beach Bum', 'IPA'),
('Uncle Bears Brewery', 'Phoenix', 'The Mutts Nuts', 'DIPA'),
('Uncle Bears Brewery', 'Phoenix', 'Barkleys Peanut Butter Cup', 'Porter'),
('Uncle Bears Brewery', 'Phoenix', 'Wolfhound Irish Red', 'Ale'),
('Uncle Bears Brewery', 'Phoenix', 'Perfecto Resado Cigar Beer', 'Ale'),
('Uncle Bears Brewery', 'Phoenix', 'English Bulldog', 'IPA'),
('Uncle Bears Brewery', 'Phoenix', 'Ruff Night', 'IPA')
