USE onTap_db;
INSERT INTO beerLists(brewery_name, city_name, beer_name, beer_type, createdAt, updatedAt)
VALUES
('XII West Brewing Co', 'Gilbert','The Weight', 'Scotch Ale', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Midnight Run', 'Stout', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Acquisitions', 'Strong Beer', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Jedi Juice', 'IPA', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Ethereal', 'Pale Ale', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Frontside', 'IPA', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Shwifty', 'Wheat Beer', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Knarbar', 'Strong Beer', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','K-LAX', 'IPA', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Super Beaker', 'IPA', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Blap! Blap', 'Wheat Beer', NOW(), NOW()),
('XII West Brewing Co', 'Gilbert','Mijo', 'Strong Beer', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert','ADHD#2', 'Pale Ale', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Boilgeist', 'IPA', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Crystal Eyes', 'Strong Beer', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'DHW: Thirsty and Miserable', 'IPA', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'DC Mmountain DIPA', 'Strong Beer', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'O-Line IPA', 'Strong Beer', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Paiute Pale Ale', 'Pale Ale', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Refuge','IPA', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Viking Tea Time', 'Lager', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Saddle Mountain', 'Saison', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Saison Sombre', 'Saison', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Salome Saison', 'Saison', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Salt River Saison', 'Saison', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Baboquivari Belgian Blonde', 'Blonde Ale', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Klothos Temple', 'IPA', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'New Brood', 'Strong Beer', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Grapefruit Gose', 'Gose', NOW(), NOW()),
('Arizona Wilderness Brewing', 'Gilbert', 'Hummingbird Springs', 'Saison', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Fence Jumper', 'Ale', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Mandarin Wheat', 'Wheat Beer', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Head to Tale', 'Ale', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Ocean Beach', 'IPA', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Bears Beach Bum', 'IPA', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'The Mutts Nuts', 'Strong Beer', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Barkleys Peanut Butter Cup', 'Porter', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Wolfhound Irish Red', 'Ale', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Perfecto Resado Cigar Beer', 'Ale', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'English Bulldog', 'IPA', NOW(), NOW()),
('Uncle Bears Brewery', 'Phoenix', 'Ruff Night', 'IPA', NOW(), NOW()),
('Four Peaks', 'Tempe','Kilt Lifter', 'Scotch Ale', NOW(), NOW()),
('Four Peaks', 'Tempe','Hop Knot', 'IPA', NOW(), NOW()),
('Four Peaks', 'Tempe','Sunbru', 'Lager', NOW(), NOW()),
('Four Peaks', 'Tempe','Oatmeal Stout', 'Stout', NOW(), NOW()),
('Four Peaks', 'Tempe','Double Knot', 'Strong Beer', NOW(), NOW()),
('Four Peaks', 'Tempe','Pitchfork', 'Pale Ale', NOW(), NOW()),
('Four Peaks', 'Tempe','Peach', 'Fruit Beer', NOW(), NOW()),
('Four Peaks', 'Tempe','8th Street Ale', 'Pale Ale', NOW(), NOW()),
('Four Peaks', 'Tempe','The Raj', 'IPA', NOW(), NOW()),
('Four Peaks', 'Tempe','White Ale', 'Wheat Beer', NOW(), NOW()),
('Sleepy Dog', 'Tempe','Red Rover', 'Ale', NOW(), NOW()),
('Sleepy Dog', 'Tempe','Tail Chaser IPA', 'IPA', NOW(), NOW()),
('Sleepy Dog', 'Tempe','Wet Snout', 'Stout', NOW(), NOW()),
('Sleepy Dog', 'Tempe','Peanut Butter Stout', 'Stout', NOW(), NOW()),
('Sleepy Dog', 'Tempe','Feisty Chihuahua', 'Lager', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Orange Bomb', 'Stout', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Bang Bang Double Black IPA', 'Strong Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','A Mountain Amber', 'Ale', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','St. Nobels Mint Chocolate Stout', 'Stout', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Greenthumb Session IPA', 'IPA', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Blasted IPA', 'IPA', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Bro Easy', 'Blonde Ale', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Extradynamit', 'Strong Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Duke of Dank', 'Strong Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Blasted Hefeweizen', 'Wheat Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Cloudy Boi', 'IPA', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Oh My Guava', 'Fruit Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Marlenes Strawberry Cream Dream', 'Ale', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Original Sin', 'Strong Beer', NOW(), NOW()),
('Blasted Barley Co', 'Tempe','Coppersmith', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Biere Blanche', 'Wheat Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Winter Solstice', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Humbolt Brown Hemp Ale', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Transatlantique Kriek Lips of Faith 2017', 'Fruit Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Bobby Jonesin For Peaches', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Puple Haze', 'Fruit Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Amber Ale', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Candi Stout', 'Stout', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Sierra Navada Pale Ale', 'Pale Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Black Ops 2017', 'Stout', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Dukes of Haze', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','BHC DIPA', 'Strong Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Noche Dulce', 'Porter', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','All Day IPA', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Voodo Ranger Juicy Haze IPA', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Betty IPA', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Green Zebra', 'Fruit Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Kentucky Breakfast Stout', 'Stout', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Rubaeus', 'Fruit Beer', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Ocean Front Property', 'Pale Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Senor Chata', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Peanut Butter Milk Stout', 'Stout', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','S.W.A.I.N Style W/O An Interesting Name', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Cali Creamin', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Solid Gold', 'Lager', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Juicy Goodnes', 'Ale', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Orderville', 'IPA', NOW(), NOW()),
('Boulders On Broadway', 'Tempe','Brunus Robustus', 'Porter', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','OHSO Hoppy', 'IPA', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','Morning Brew', 'Stout', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','Popcycle Blonde', 'Fruit Beer', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','Lost Viking', 'Porter', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','OHSO Brite', 'Lager', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','Orange Pedal', 'Fruit Beer', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','Handlebar Hefe', 'Wheat Beer', NOW(), NOW()),
('OHSO Brewery', 'Gilbert','89 Ale', 'Ale', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Devils Ale', 'Pale Ale', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','HopShock IPA', 'IPA', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Mr Pineapple', 'Fruit Beer', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','San Tan Hefeweizen', 'Wheat Beer', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','MoonJuice Grapefruit IPA', 'Fruit Beer', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','MoonJuice IPA', 'IPA', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','SunSpot Gold', 'Ale', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Epicenter Amber', 'Ale', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Gordo Stout', 'Stout', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','LimeLeaf', 'Fruit Beer', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','San Tan Oktoberfest', 'Lager', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Sex Panther', 'Porter', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Yotes Pale Ale', 'Pale Ale', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Kilohop', 'Strong Beer', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Count Hopula', 'IPA', NOW(), NOW()),
('San Tan Brewing Co', 'Chandler','Winter Warmer', 'Strong Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Joker Amber Ale', 'Ale', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Clown Shoes Mango', 'Lager', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Framboise Rose Gose', 'Gose', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Pulp Fusion', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Wit-ty Assistant', 'Wheat Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Hatch Chile Gatos', 'Fruit Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Old Rasputin', 'Stout', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Cutthroat Porter', 'Porter', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Storming the Castle', 'Strong Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Two Cents', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Wit O Honey', 'Wheat Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Bloody Flockn Haze', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Burd Light', 'Lager', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Belgian Peach', 'Fruit Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Vaca Milk Stout', 'Stout', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Pockets Pale Ale', 'Pale Ale', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Bird Cafe', 'Ale', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Belgian Blackberry', 'Fruit Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Mango Reverso', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch DGS Pink Boots Collab', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch Bird Games', 'Fruit Beer', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch De Puanu', 'Saison', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','The Perch People Overwhelm Me', 'IPA', NOW(), NOW()),
('The Perch Brewery Co', 'Chandler','Stiegl Radler Grapefruit Naturtrub', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Pabst Blue Ribbon', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Coors Light', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Miller Lite', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Dos Equis', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Coronal Light', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Coors Banquet', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Bud Light', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Michelob Ultra', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Stella Artois', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Budweiser', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Sierra Ora Vez', 'Gose', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Rolling Rock', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Miller High Life', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Light Me Up', 'Lager', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Huss Scottsdale Blonde', 'Blonde Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Fat Tire', 'Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Saint Archer', 'IPA', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Citrus Mistress IPA', 'IPA', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Fruli Strawberry', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','New Castle', 'Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Pitchfork Pale Ale', 'Pale Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Peach Ale', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Kiltlifter', 'Scotch Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Firestone Walker 805', 'Blonde Ale', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Fresh Squeezed IPA', 'IPA', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Goose IPA', 'IPA', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Hop Knot IPA', 'IPA', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Blue Moon', 'Wheat Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Purple Haze', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Grapefruit Shandy', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Leinenkugel Seasonal', 'Fruit Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Shock Top', 'Wheat Beer', NOW(), NOW()),
('Dierks Bentleys Whiskey Row', 'Tempe','Santan Hefeweizen', 'Wheat Beer', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Space Melon', 'IPA', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','GKnight', 'IPA', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Imperial Russian Stout', 'Stout', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','American Hoppy Lager', 'Lager', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Good Morning Beautiful', 'Ale', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Coconut Coffee Export Stout', 'Stout', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Juicy Pinball', 'Pale Ale', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Lucy Foss', 'Pale Ale', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Double Knot', 'IPA', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Tradecraft Series Blackberry Sour', 'Gose', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Mod Project Berliner Weisse', 'Gose', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Noche Dulce', 'Porter', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Burbon Barrel Aged Kiltlifter', 'Scotch Ale', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Oh My Gatos', 'Ale', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','What Would Jess Drink', 'IPA', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Millennium Falcons Flight', 'IPA', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Wild Sour Series Blueberry Gose', 'Gose', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Umbrix Rye Imperial Stout', 'Stout', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','St Jameson', 'Stout', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Burbon Barrel Aged Ground Control', 'Stout', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Transatlantique Kriek Lips of Faith 2016', 'Fruit Beer', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Berlin Weisse Cranberry Quince', 'Gose', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Light Lager', 'Lager', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Phoenix Rising Lager', 'Lager', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Belgian Tripel', 'Strong Beer', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Franziskaner Hefe-Weissbier', 'Wheat Beer', NOW(), NOW()),
('Yucca Tap Room', 'Tempe','Milk Stout', 'Stout', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Morning Sex', 'Stout', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Chronic Amber Ale', 'Ale', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Stone Totalitarian Imperial Russian Stout', 'Stout', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Oatmeal Stout', 'Stout', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Imagination Land', 'Stout', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','805 Blonde', 'Blonde Ale', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Booming Rollers', 'IPA', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Three Skulls Blood Orange Wit', 'Wheat Beer', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Iron Horse Hoppy Golden', 'IPA', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','American Lager', 'Lager', NOW(), NOW()),
('Fox Cigar Bar', 'Gilbert','Brunus Robustus', 'Porter', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Acoustic Ales Unplugged', 'Stout', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Avery Old Jubilation Ale', 'Strong Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Barrio Citrazona', 'IPA', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Coronado Peach Cruiser', 'IPA', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Deschutes Mirror Pond', 'Pale Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Figueroa Mountain Paridise Road', 'Lager', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Great Divide Colette', 'Saison', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Iron Fist Nelson The Impaler', 'Pale Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Lagunitas Cappuccino Stout', 'Stout', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Mike Hess Grazias Vienna Cream', 'Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','New Belgium 1554', 'Lager', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','North Coast Brother Thelonious', 'Strong Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Oskar Blues Dales', 'Pale Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Pizza Port Pickleweed Point', 'IPA', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Saint Archer Mosaic Double IPA', 'Strong Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Anderson Valley Winter Solstice', 'Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Avery White Rascal', 'Wheat Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Boulevard Rye On Rye', 'Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Destihl Brewery Weissenheimer Hefeweizen', 'Wheat Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Dogfish Head 60 Minute IPA', 'IPA', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Full Sail Session', ' Lager', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Helton', 'Scotch Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','La Cumbre Malpais', 'Stout', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Marble Imperial Red', 'IPA', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Modern Times Lomaland', 'Saison', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Newcastle Ale', 'Ale', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Northwest Three Skulls Blood Orange Wit', 'Wheat Beer', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Pizza Port Bacon and Eggs Imperial Coffee Porter', 'Porter', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Prairie Artisan Ales Standard', 'Saison', NOW(), NOW()),
('Angels Trumpet Ale House', 'Phoenix','Samuel Smith Nut Ale', 'Ale', NOW(), NOW())